<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Justin Kim, Aryan Arora, Shuri Yamamoto and Erhan Asad Javed">

<title>White Wine Quality Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary"><span class="header-section-number">1</span> Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description"><span class="header-section-number">2.1</span> Data Description</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#dataset-data-cleaning" id="toc-dataset-data-cleaning" class="nav-link" data-scroll-target="#dataset-data-cleaning"><span class="header-section-number">3.1</span> Dataset &amp; Data Cleaning</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">3.2</span> Exploratory Data Analysis</a></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">3.3</span> Prediction</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#loading-the-dataset-data-wrangling" id="toc-loading-the-dataset-data-wrangling" class="nav-link" data-scroll-target="#loading-the-dataset-data-wrangling"><span class="header-section-number">4.1</span> Loading the Dataset &amp; Data Wrangling</a></li>
  <li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1"><span class="header-section-number">4.2</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#inspecting-the-dataset-structure" id="toc-inspecting-the-dataset-structure" class="nav-link" data-scroll-target="#inspecting-the-dataset-structure"><span class="header-section-number">4.2.1</span> Inspecting the dataset structure</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#prediction-1" id="toc-prediction-1" class="nav-link" data-scroll-target="#prediction-1"><span class="header-section-number">5</span> Prediction</a>
  <ul class="collapse">
  <li><a href="#model-construction" id="toc-model-construction" class="nav-link" data-scroll-target="#model-construction"><span class="header-section-number">5.0.1</span> Model Construction</a></li>
  <li><a href="#grid-search" id="toc-grid-search" class="nav-link" data-scroll-target="#grid-search"><span class="header-section-number">5.0.2</span> Grid Search</a></li>
  <li><a href="#model-evaluation-on-test-data" id="toc-model-evaluation-on-test-data" class="nav-link" data-scroll-target="#model-evaluation-on-test-data"><span class="header-section-number">5.0.3</span> Model Evaluation on Test Data</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">White Wine Quality Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Justin Kim, Aryan Arora, Shuri Yamamoto and Erhan Asad Javed </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary</h1>
<p>This study explored the physicochemical characteristics of white wines and their relationship with quality ratings using exploratory data analysis and machine learning. The analysis showed that most wines fall within mid-range quality scores, with relatively few very low or very high ratings. Several chemical variables exhibit skewed distributions and occasional extreme values, while correlations suggest that wine quality is influenced by multiple factors rather than a single dominant variable. A random forest model was used to predict wine quality, achieving moderate accuracy but showing lower performance on minority classes due to class imbalance. These findings highlight the complexity of predicting wine quality and suggest that future work could improve results by addressing class imbalance and exploring more advanced models.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>The goal of this project is to analyze and predict white wine quality based on physicochemical properties such as alcohol content, acidity, and sugar levels. Understanding the factors that influence wine quality can help producers improve production processes and ensure consistent product quality.</p>
<p>Previous research has demonstrated that data mining and machine learning techniques can effectively model wine quality using physicochemical attributes <span class="citation" data-cites="cortez2009">Cortez et al. (<a href="#ref-cortez2009" role="doc-biblioref">2009</a>)</span>. Additionally, ensemble learning approaches have been shown to improve predictive performance in similar classification problems <span class="citation" data-cites="sagi2018">Sagi and Rokach (<a href="#ref-sagi2018" role="doc-biblioref">2018</a>)</span>.</p>
<p>This analysis aims to identify key variables that impact wine quality and evaluate how well these variables can be used to predict quality outcomes.</p>
<section id="data-description" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-description"><span class="header-section-number">2.1</span> Data Description</h2>
<p>The dataset used in this analysis contains measurements of various physicochemical properties of white wine samples. These include variables such as alcohol content, pH, density, residual sugar, and other chemical characteristics.</p>
<p>The target variable is wine quality, which is measured on a numerical scale. This dataset enables the exploration of relationships between these features and wine quality, forming the basis for predictive modeling.</p>
</section>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<p>To analyze the relationship between physicochemical properties and wine quality, a predictive modeling approach was used. The dataset was first cleaned and preprocessed to ensure consistency and accuracy.</p>
<p>Machine learning techniques are commonly applied in predictive modeling tasks due to their ability to capture complex relationships between variables <span class="citation" data-cites="rodriguez2015">Rodriguez-Galiano et al. (<a href="#ref-rodriguez2015" role="doc-biblioref">2015</a>)</span>. In this analysis, an appropriate model was selected to identify key predictors of wine quality and evaluate predictive performance.</p>
<p>Model performance was assessed using relevant evaluation metrics to determine how accurately wine quality could be predicted.</p>
<section id="dataset-data-cleaning" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="dataset-data-cleaning"><span class="header-section-number">3.1</span> Dataset &amp; Data Cleaning</h2>
<p>The Wine Quality dataset is retrieved directly from the <strong>UCI Machine Learning Repository</strong> using the <code>ucimlrepo</code> library. The dataset is returned with the features (input variables) and the target variable (wine quality score) stored separately.</p>
<p>To recreate the original dataset structure, we combine the features and target into a single DataFrame using <code>pd.concat()</code>. This produces a table where each row represents a wine sample and each column represents a physicochemical property or the quality score. However, this results in a DataFrame that contains both red and white wine data. Since we only aim to use white wine data, we clean the data by dropping the first 1599 samples, which correspond to red wine data, leaving only the 4898 white wine samples.</p>
</section>
<section id="exploratory-data-analysis" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">3.2</span> Exploratory Data Analysis</h2>
<p>Since EDA is generally performed after splitting the data, we first split the dataset into training and test sets, and then perform EDA using the training set. The dataset is initially split with a 70/30 ratio, and train set is further split into train and validation sets. Consequently, train set contains 2708 samples, validation set contains 720 samples, and test set contains 1470 samples. Figure 1 also visualizes the proportion of each dataset.</p>
<p>We examine the basic structure of the dataset by checking its shape, column names, data types, missing values, and statistical summary of each feature using the following functions: - <code>df.shape</code> shows the number of rows and columns in the dataset. - <code>df.columns</code> lists all variable names. - <code>df.info()</code> provides the data type of each column and a summary of non-null values. - <code>df.isnull().sum()</code> counts the number of missing values in each column. - <code>df.describe()</code> provides summary statistics such as mean, standard deviation, and range for numerical variables.</p>
<p>We visualize the distribution of the target variable <code>quality</code> using a bar chart. The values are counted using <code>value_counts()</code> and sorted by quality score to show how many wines fall into each rating category. This helps us understand how wine quality scores are distributed across the dataset.</p>
<p>We generate histograms for each feature in the dataset using <code>df.hist()</code>. This allows us to visualize the distribution of values for each variable and observe patterns such as skewness, spread, and potential outliers across the physicochemical properties of the wines.</p>
<p>Lastly, we compute the correlation matrix using <code>df.corr()</code> to measure the linear relationships between all numerical variables in the dataset. The matrix is then visualized using <code>plt.imshow()</code>, where each cell represents the correlation between two variables.</p>
</section>
<section id="prediction" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="prediction"><span class="header-section-number">3.3</span> Prediction</h2>
<p>The random forest classifier is used to build a model to predict white wine quality. Since the random forest classifier is scale-invariant, we do not scale the data before training.</p>
<p>Grid search is used to explore various combinations of hyperparameters, and the best performing model with 20 <code>max_depth</code> and 100 <code>n_estimators</code> is achieved.</p>
<p>The best model is evaluated using a classification report, which shows that the test accuracy, precison, recall, and F1-score. Figure 5 visualizes the confusion matrix on the test data to further examine its classification performance across different target classes.</p>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="loading-the-dataset-data-wrangling" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="loading-the-dataset-data-wrangling"><span class="header-section-number">4.1</span> Loading the Dataset &amp; Data Wrangling</h2>
</section>
<section id="exploratory-data-analysis-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="exploratory-data-analysis-1"><span class="header-section-number">4.2</span> Exploratory Data Analysis</h2>
<div id="d6ceb11b" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-5-output-1.png" width="470" height="483" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Train set length: 2708 | Validation set length: 720 | Test set length: 1470
</code></pre>
</div>
</div>
<p>Train set length: 2708 | Validation set length: 720 | Test set length: 1470</p>
<section id="inspecting-the-dataset-structure" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="inspecting-the-dataset-structure"><span class="header-section-number">4.2.1</span> Inspecting the dataset structure</h3>
<div id="2a48c71c" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Shape of dataset: (2708, 11)

Column names:['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol']</code></pre>
</div>
</div>
<div id="8018a1af" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>
Data types and info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
Index: 2708 entries, 5497 to 4053
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed_acidity         2708 non-null   float64
 1   volatile_acidity      2708 non-null   float64
 2   citric_acid           2708 non-null   float64
 3   residual_sugar        2708 non-null   float64
 4   chlorides             2708 non-null   float64
 5   free_sulfur_dioxide   2708 non-null   float64
 6   total_sulfur_dioxide  2708 non-null   float64
 7   density               2708 non-null   float64
 8   pH                    2708 non-null   float64
 9   sulphates             2708 non-null   float64
 10  alcohol               2708 non-null   float64
dtypes: float64(11)
memory usage: 253.9 KB</code></pre>
</div>
</div>
<div id="0bcda85d" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Missing values per column:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="39">
<pre><code>fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
dtype: int64</code></pre>
</div>
</div>
<div id="6b3a7b44" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Summary statistics:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fixed_acidity</th>
<th data-quarto-table-cell-role="th">volatile_acidity</th>
<th data-quarto-table-cell-role="th">citric_acid</th>
<th data-quarto-table-cell-role="th">residual_sugar</th>
<th data-quarto-table-cell-role="th">chlorides</th>
<th data-quarto-table-cell-role="th">free_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">total_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">density</th>
<th data-quarto-table-cell-role="th">pH</th>
<th data-quarto-table-cell-role="th">sulphates</th>
<th data-quarto-table-cell-role="th">alcohol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
<td>2708.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>6.846270</td>
<td>0.280835</td>
<td>0.335454</td>
<td>6.462832</td>
<td>0.046059</td>
<td>35.533789</td>
<td>139.034712</td>
<td>0.994057</td>
<td>3.184487</td>
<td>0.491562</td>
<td>10.493405</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>0.828504</td>
<td>0.101603</td>
<td>0.120338</td>
<td>5.172827</td>
<td>0.022880</td>
<td>17.545857</td>
<td>42.560629</td>
<td>0.003072</td>
<td>0.149090</td>
<td>0.116900</td>
<td>1.228132</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>3.800000</td>
<td>0.080000</td>
<td>0.000000</td>
<td>0.600000</td>
<td>0.009000</td>
<td>2.000000</td>
<td>18.000000</td>
<td>0.987110</td>
<td>2.720000</td>
<td>0.230000</td>
<td>8.000000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>6.300000</td>
<td>0.210000</td>
<td>0.270000</td>
<td>1.700000</td>
<td>0.036000</td>
<td>24.000000</td>
<td>110.000000</td>
<td>0.991720</td>
<td>3.080000</td>
<td>0.410000</td>
<td>9.400000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>6.800000</td>
<td>0.260000</td>
<td>0.320000</td>
<td>5.300000</td>
<td>0.043000</td>
<td>34.000000</td>
<td>134.000000</td>
<td>0.993700</td>
<td>3.170000</td>
<td>0.480000</td>
<td>10.300000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>7.300000</td>
<td>0.330000</td>
<td>0.390000</td>
<td>9.900000</td>
<td>0.050000</td>
<td>45.000000</td>
<td>168.000000</td>
<td>0.996130</td>
<td>3.280000</td>
<td>0.550000</td>
<td>11.400000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>14.200000</td>
<td>1.005000</td>
<td>1.000000</td>
<td>65.800000</td>
<td>0.346000</td>
<td>289.000000</td>
<td>440.000000</td>
<td>1.038980</td>
<td>3.770000</td>
<td>1.080000</td>
<td>14.200000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="939a1a44" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-10-output-1.png" width="602" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2 shows that the distribution of wine quality scores is concentrated around the middle values. Most wines are rated 5, 6, or 7, with quality 6 being the most frequent. Very few wines receive extreme ratings such as 3 or 9, indicating that the dataset contains mostly average-quality wines and relatively few very poor or excellent samples. This indicates a significant class imbalance. Moreover, although the UCI Machine Learning Repository lists the wine quality feature ranging from 0 to 10, there are no samples for 0, 1, 2 and 10, and thus the model will never encounter these classes during training. These issues raise concerns that model may perform poorly on the minority classes, which correspond to extremely low or high quality wines.</p>
<div id="97a0519c" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-11-output-1.png" width="965" height="877" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Figure 3 shows that most physicochemical variables fall within fairly narrow ranges. For example, pH values are centered around 3.1 with a small spread, and density is close to 0.995 for most wines. Alcohol content ranges roughly from 9% to 14%, with an average around 10.5%. In contrast, residual sugar varies much more widely, ranging from under 1 to over 60, indicating some extreme observations.</p>
<p>The figure also suggests that several variables are right-skewed, meaning most wines have lower values with a few much larger observations. This pattern is especially noticeable for chlorides, residual sugar, sulphates, and fixed acidity. Total sulfur dioxide appears roughly more evenly distributed around the average.</p>
<div id="6dc53441" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-12-output-1.png" width="669" height="630" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4 shows the strength and direction of linear relationships between the variables. Overall, most physicochemical features have relatively weak correlations with wine quality, suggesting that quality is influenced by multiple factors rather than a single dominant variable. Alcohol content tends to have a positive relationship with quality, while variables such as volatile acidity and density show negative relationships. Many of the input variables also show moderate correlations with each other, indicating that some chemical properties of the wine are related.</p>
</section>
</section>
</section>
<section id="prediction-1" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Prediction</h1>
<p>To model wine quality, we require a method that can capture complex and potentially non-linear relationships between physicochemical features such as acidity, sugar content, and alcohol level. Preliminary exploration suggests that these variables may interact in ways that are not well represented by simple linear models. Additionally, the dataset contains multiple continuous predictors with possible correlations and varying scales, making model flexibility important. For this reason, we turn to the Random Forest algorithm, an ensemble learning method that builds multiple decision trees and aggregates their predictions. Random Forest is well-suited for this task because it can handle non-linear patterns, is robust to overfitting through averaging, and provides insight into feature importance, allowing us to better understand which factors most strongly influence wine quality.</p>
<section id="model-construction" class="level3" data-number="5.0.1">
<h3 data-number="5.0.1" class="anchored" data-anchor-id="model-construction"><span class="header-section-number">5.0.1</span> Model Construction</h3>
<p>We will use Grid Search to systematically test different hyperparameter combinations and find the best-performing version of the model. This helps improve predictive accuracy and makes the tuning process more reliable and reproducible.</p>
</section>
<section id="grid-search" class="level3" data-number="5.0.2">
<h3 data-number="5.0.2" class="anchored" data-anchor-id="grid-search"><span class="header-section-number">5.0.2</span> Grid Search</h3>
<div id="33d64fff" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Best parameters found from grid search: {'max_depth': 30, 'n_estimators': 100}</code></pre>
</div>
</div>
</section>
<section id="model-evaluation-on-test-data" class="level3" data-number="5.0.3">
<h3 data-number="5.0.3" class="anchored" data-anchor-id="model-evaluation-on-test-data"><span class="header-section-number">5.0.3</span> Model Evaluation on Test Data</h3>
<div id="d7c17dbd" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-16-output-1.png" width="513" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="3e29c431" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.16      0.50      0.25        14
           5       0.64      0.67      0.65       411
           6       0.76      0.65      0.70       820
           7       0.51      0.58      0.55       208
           8       0.28      0.88      0.42        17
           9       0.00      0.00      0.00         0

    accuracy                           0.65      1470
   macro avg       0.34      0.47      0.37      1470
weighted avg       0.68      0.65      0.66      1470
</code></pre>
</div>
</div>
<p>We evaluate model performance using accuracy, precision, recall, and F1-score. While accuracy measures overall correctness, precision shows how reliable positive predictions are, recall measures how well actual positives are identified, and F1-score balances precision and recall, making it especially useful under class imbalance. The definitions are as follows: - Accuracy: - Formula: <span class="math inline">\(\frac{TP + TN}{TP + TN + FP + FN}\)</span> - Definition: proportion of correct classifications out all predictions. - Precision: - Formula: <span class="math inline">\(\frac{TP}{TP+FP}\)</span> - Definition: proportion of correct positive predictions out all positive predictions. It tells you how much of the model’s positive predictions is correct. - Recall: - Formula: <span class="math inline">\(\frac{TP}{TP+FN}\)</span> - Definition: proportion of correct positive predictions out of actual positive sampples. It tells you how many actual positive samples the model can capture. - F1-score: - Formula: <span class="math inline">\(2 \times \frac{Precision \times Recall}{Precision + Recall}\)</span> - Definition: F1-score is a harmonic mean of precision and recall. It tells you the model’s classification performance by addressing both precision and recall. To achieve a high F1-score, both precision and recall should be high enough.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussion</h1>
<p>The exploratory data analysis suggests that most wines in the dataset fall into average quality categories, with ratings concentrated around the middle of the scale. This indicates that class imbalance in which extremely high or low quality wines are relatively uncommon. The distributions of many physicochemical variables show that most measurements lie within typical ranges, although some variables such as residual sugar and chlorides exhibit wider spreads and occasional extreme values. Several variables also appear right-skewed, meaning most wines have relatively small values with a few larger observations. This pattern suggests that certain chemical properties occur at low levels for most wines but can occasionally be much higher. The correlation analysis further indicates that no single variable strongly determines wine quality. Instead, wine quality appears to be influenced by a combination of multiple chemical characteristics, with some variables showing modest positive or negative relationships with the quality score.</p>
<p>The random forest classifier with <code>max_depth</code> of 20 and <code>n_estimator</code> of 100 is achieved through grid search. Our model achieves a macro test accuracy of 65%, a precision of 34%, a recall of 50%, and an F1-score of 38%, showing a sign of underperformance in predicting white wine quality. Since our task is more complex than binary classification, this result is expected, as the random forest model is not the most powerful model for this task compared to other approaches such as MLPs. Similar studies have found that machine learning can identify relationships between chemical composition and wine quality, but prediction accuracy often depends on model choice and feature representation (Rodriguez-Galiano et al., 2015; Sagi &amp; Rokach, 2018). Moreover, the model exhibits a biased performance favoring the dominant classes. This behavior is expected as currently no method is applied to handle class imbalance. Hence, for future work, we suggest to handle class imbalance with up/oversampling or reweighing to improve fairness and perfrmance across all classes.</p>
<p>Future work could explore methods to address class imbalance, such as oversampling or class weighting, to improve prediction across all quality levels. In addition, testing more advanced models such as gradient boosting or neural networks may help capture more complex relationships between variables. Further research could also examine whether additional information, such as sensory or production data, improves predictive performance.</p>
</section>
<section id="references" class="level1 unnumbered" data-number="7">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">7 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-cortez2009" class="csl-entry" role="listitem">
Cortez, Paulo, António Cerdeira, Fernando Almeida, Telmo Matos, and José Reis. 2009. <span>“Modeling Wine Preferences by Data Mining from Physicochemical Properties.”</span> <em>Decision Support Systems</em>.
</div>
<div id="ref-rodriguez2015" class="csl-entry" role="listitem">
Rodriguez-Galiano, Vı́ctor, Margarita Sanchez-Castillo, Mario Chica-Olmo, and Marı́a J. Chica-Rivas. 2015. <span>“Machine Learning Predictive Models for Mineral Prospectivity: An Evaluation of Neural Networks, Random Forest, Regression Trees and Support Vector Machines.”</span> <em>Ore Geology Reviews</em> 71: 804–18.
</div>
<div id="ref-sagi2018" class="csl-entry" role="listitem">
Sagi, Omer, and Lior Rokach. 2018. <span>“Ensemble Learning: A Survey.”</span> <em>Wiley Interdisciplinary Reviews: Data Mining and Knowledge Discovery</em> 8 (4): e1249.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>